image: node:latest

    stages:
      - build

    build_app:
      only:
          - master
      stage: build
      script:
        - echo "Building Application"
        - npm install
        - npm run client-build
